# Generated by Django 5.1.1 on 2024-09-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('Client', 'Client'), ('Agent', 'Agent')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Rent', 'Rent')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='str_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='str_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
    ]
