# Generated by Django 5.1.1 on 2024-09-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_client_category_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'get_latest_by': 'order_date'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'get_latest_by': 'order_date'},
        ),
    ]
