# Generated by Django 5.1.1 on 2024-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_client_options_alter_listing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
