# Generated by Django 5.1.1 on 2024-09-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
