# Generated by Django 5.1.1 on 2024-09-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_listing_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='listing',
            name='str_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Street Number'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='str_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Name'),
        ),
    ]
