# Generated by Django 5.1.1 on 2024-09-15 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_coordinates_listing_city_listing_str_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='listing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='base.listing'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='coordinates',
            table='coordinates',
        ),
    ]
